repos:
  - repo: https://github.com/psf/black
    rev: '21.5b1'
    hooks:
      - id: black
        additional_dependencies: ['click==8.0.4']
        language_version: python3
        files: '^python/'
