repos:
  - repo: https://github.com/psf/black
    rev: '21.5b1'
    hooks:
      - id: black
        language_version: python3
        files: '^python/'
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        language_version: python3
        files: '^python/'
