-

  type: adcm
  name: ADCM
  version: 1.4

  config:
    - name: "global"
      display_name: "Global Options"
      type: "group"
      subs:
        - name: "adcm_url"
          display_name: "ADCM's URL"
          description: |
            We have to know ADCM's Url to send information from host. We try to gues that information from url you enter in browser.
            But if your network has more complicated structure and we gues wrong, please fix that here.
          type: string
    - name: "google_oauth"
      display_name: "Google Auth"
      type: "group"
      subs:
        - name: "client_id"
          type: string
          required: false
        - name: "secret"
          type: password
          required: false
          ui_options:
            no_confirm: true
        - name: "whitelisted_domains"
          type: list
          required: false
    - name: "job_log"
      display_name: "Job Log"
      type: "group"
      subs:
        - name: "log_rotation_on_fs"
          display_name: "Log rotation from file system"
          type: integer
          required: false
          default: 365
          min: 0
          description: |
            You can set the time (number of days) after which the logs will be deleted from the file system.
        - name: "log_rotation_in_db"
          display_name: "Log rotation from database"
          type: integer
          required: false
          default: 365
          min: 0
          description: |
            You can set the time (number of days) after which the logs will be deleted from the database.
    - name: "ansible_settings"
      display_name: "Ansible Settings"
      type: "group"
      subs:
        - name: "mitogen"
          display_name: "Use Mitogen"
          description: |
            Mitogen for Ansible is a completely redesigned UNIX connection layer and module runtime for Ansible.
          type: boolean
          ui_options:
            invisible: true
          default: false
        - name: "forks"
          display_name: "Forks"
          description: |
            This is the default number of parallel processes to spawn when communicating with remote hosts.
          type: integer
          default: 5
          min: 1
          max: 100
    - name: "logrotate"
      display_name: "Logrotate"
      type: "group"
      subs:
        - name: "rotation_period"
          display_name: "Rotation period"
          description: |
            Rotation period
          type: option
          option:
            HOURLY: "HOURLY"
            DAILY: "DAILY"
            WEEKLY: "WEEKLY"
          default: "DAILY"
        - name: "nginx_server"
          display_name: "Nginx Server"
          description: |
            Rotation logs for nginx server
          type: boolean
          default: false
